#!/usr/bin/env bash
# Cut a release in two steps, with a review in between.
#
#   scripts/release.sh <patch|minor|major|current>   prepare: bump the
#       workspace version, regenerate CHANGELOG.md, infer the docs changelog
#       snippets, compose docs/changelog.mdx — and STOP, leaving it all
#       uncommitted for review. `current` prepares the existing version
#       without bumping (first release).
#   scripts/release.sh publish                        after the review: recompose
#       the docs page from the (possibly edited) snippets, commit as
#       chore(release): vX.Y.Z, tag vX.Y.Z, push. The pushed tag triggers
#       .github/workflows/release.yaml.
#   scripts/release.sh abort                          drop a prepared release.
set -euo pipefail

command="${1:?usage: release.sh <patch|minor|major|current|publish|abort>}"

# Everything a prepared release touches. `publish` refuses a tree that is
# dirty anywhere else, and `abort` restores exactly this set.
release_files=(Cargo.toml Cargo.lock CHANGELOG.md docs/docs.json docs/changelog.mdx docs/snippets/changelog)

require_main() {
  local branch
  branch=$(git rev-parse --abbrev-ref HEAD)
  [ "$branch" = "main" ] || { echo "must release from main (on $branch)" >&2; exit 1; }
  git fetch -q origin main
  [ "$(git rev-parse HEAD)" = "$(git rev-parse origin/main)" ] || { echo "main is not in sync with origin" >&2; exit 1; }
}

# The changelog is generated by graph's own plans (changelog_entry,
# compose_changelog), so a missing or too-old binary fails fast, before
# anything is mutated.
require_graph() {
  command -v graph >/dev/null || { echo "graph not found on PATH — the changelog plans need it (mise run install)" >&2; exit 1; }
  GRAPH_STORAGE=memory graph plan validate compose_changelog >/dev/null \
    || { echo "compose_changelog does not validate — graph on PATH too old? (needs >= v0.10.0 for filter steps)" >&2; exit 1; }
}

# The file-version constants (docs/reference/file-versions.mdx) at a ref, one
# "<name> <version>" per line. A ref that predates a kind's constant reads
# as "-": that kind had no version yet, and its first release announces it
# as new rather than as a bump.
format_table() {
  local ref=$1
  for spec in \
    "config crates/graph-config/src/format.rs CONFIG_FORMAT" \
    "plan crates/graph-core/src/format.rs PLAN_FORMAT" \
    "tool crates/graph-core/src/format.rs TOOL_FORMAT" \
    "store crates/graph-store/src/file.rs STORE_FORMAT"; do
    set -- $spec
    source=$(git show "$ref:$2" 2>/dev/null || true)
    version=$(printf '%s\n' "$source" | sed -n "s/^pub const $3: u32 = \([0-9]*\);.*/\1/p" | head -1)
    echo "$1 ${version:--}"
  done
}

# Everything both steps must agree on, derived from the same facts each
# time (the last tag, the constants at HEAD, the unreleased commits):
# format_delta, file_versions, tag_message, and the unreleased context.
# `publish` runs it again rather than trusting anything `prepare` wrote
# down — a review may have changed nothing, or everything.
resolve_release() {
  local new=$1
  last_tag=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || true)
  format_delta=""
  if [ -n "$last_tag" ]; then
    format_delta=$(paste -d' ' <(format_table "$last_tag") <(format_table HEAD) \
      | awk '$2 != "-" && $2 != $4 { printf "%s %s→%s\n", $1, $2, $4 }' | paste -sd',' - | sed 's/,/, /g')
  fi
  unreleased=$(git-cliff --tag "v$new" --unreleased --context 2>/dev/null)
  breaking=$(jq '[.[] | .commits[]? | select(.breaking == true)] | length' <<<"$unreleased")

  # A breaking commit scoped `config`/`plan`/`tool`/`store` becomes that file
  # kind's own changelog entry, so the scope and the constant must agree both
  # ways: a moved constant needs a commit that documents it, and a
  # reserved-scope commit needs a moved constant (or it is a misfiled crate
  # change — pick another scope). The footer has to name the new version, since
  # that line is what the changelog prints next to the subject. A kind that had
  # no constant at the last tag is announced as new instead, with no commit
  # required — its first entry says so.
  file_versions=""
  for spec in $(format_table HEAD | tr ' ' '='); do
    kind=${spec%%=*}; now=${spec#*=}
    was=$(format_table "${last_tag:-HEAD}" | awk -v k="$kind" '$1 == k { print $2 }')
    scoped=$(jq -r --arg k "$kind" '[.[] | .commits[]? | select(.breaking == true and .scope == $k)] | length' <<<"$unreleased")
    if [ "$now" = "-" ]; then
      echo "no $kind version constant at HEAD" >&2; exit 1
    elif [ "$was" = "-" ]; then
      file_versions="${file_versions:+$file_versions, }$kind $now (new)"
    elif [ "$now" != "$was" ]; then
      [ "$scoped" -gt 0 ] || { echo "$kind version moved $was→$now but no breaking commit is scoped ($kind) — the changelog cannot document it" >&2; exit 1; }
      jq -e --arg k "$kind" --arg n "$now" \
        '[.[] | .commits[]? | select(.breaking == true and .scope == $k)] | all(.breaking_description | test("\($k) version \($n)\\b"))' \
        <<<"$unreleased" >/dev/null \
        || { echo "every ($kind)! commit needs a footer 'BREAKING CHANGE: $kind version $now …' (see RELEASING.md > Version bumps)" >&2; exit 1; }
      file_versions="${file_versions:+$file_versions, }$kind $now (from $was)"
    else
      [ "$scoped" -eq 0 ] || { echo "a commit is scoped ($kind)! but the $kind version did not move — reserved scopes mean a version bump" >&2; exit 1; }
      file_versions="${file_versions:+$file_versions, }$kind $now"
    fi
  done
  tag_message="graph v$new

file versions: $file_versions"
  # git-cliff reads the not-yet-created tag's message from here, so the
  # CHANGELOG and the docs page render this release's entries now, exactly
  # as a regeneration will after the tag exists.
  export GIT_CLIFF_WITH_TAG_MESSAGE="$tag_message"
}

prepare() {
  local level=$1
  require_main
  [ -z "$(git status --porcelain)" ] || { echo "working tree not clean" >&2; exit 1; }
  require_graph

  current=$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -1)
  IFS=. read -r major minor patch <<<"$current"
  case "$level" in
    major)   new="$((major + 1)).0.0" ;;
    minor)   new="$major.$((minor + 1)).0" ;;
    patch)   new="$major.$minor.$((patch + 1))" ;;
    current) new="$current" ;;
  esac
  if git rev-parse "v$new" >/dev/null 2>&1; then
    echo "tag v$new already exists" >&2; exit 1
  fi

  resolve_release "$new"

  # A file-version bump or a breaking commit is a release-level decision, not
  # a patch: pre-1.0 it needs at least a minor, from 1.0 on it needs a major.
  if [ -n "$format_delta" ] || [ "${breaking:-0}" -gt 0 ]; then
    echo "release carries breaking changes: ${breaking:-0} breaking commit(s)${format_delta:+, file-version bump(s): $format_delta}"
    needed=$([ "$major" -ge 1 ] && echo major || echo minor)
    case "$level:$needed" in
      major:*|minor:minor|current:*) ;;
      *) echo "a breaking release needs at least a $needed bump (got $level)" >&2; exit 1 ;;
    esac
  fi

  # A release needs at least one changelog-worthy commit. git-cliff emits no
  # section at all for a tag whose commits are every one ci:/chore:/test:, and
  # the release would then strand halfway — version bumped, CHANGELOG.md
  # rewritten, then changelog_entry failing with no release to describe and a
  # dirty tree to clean up by hand. Checked here, before anything is mutated.
  worthy=$(jq '[.[] | .commits[]? | select(.group != null)] | length' <<<"$unreleased")
  [ "$worthy" -gt 0 ] || {
    echo "nothing to release: no changelog-worthy commits since the last tag" >&2
    echo "(everything since is ci:/chore:/test:, which the changelog skips)" >&2
    exit 1
  }

  echo "preparing v$new (was $current)"

  if [ "$level" != "current" ]; then
    # Bump the single workspace version (crates inherit it). The full-line
    # anchor matches only the workspace field, so plain s/// is safe — and
    # portable: GNU-only "0,/re/" addressing silently no-ops on BSD sed.
    sed -i.bak "s/^version = \"$current\"\$/version = \"$new\"/" Cargo.toml && rm Cargo.toml.bak
    grep -q "^version = \"$new\"\$" Cargo.toml || { echo "version bump failed" >&2; exit 1; }
    # Refresh Cargo.lock's version entries.
    cargo update -q --workspace
    # Keep the docs in step: {{release_version}} feeds the installation
    # page, download cards, and cookbook image pins. Key-anchored so a
    # drifted value fails the grep below instead of shipping stale docs —
    # and since the release commit touches docs/, it also triggers the
    # Mintlify rebuild that publishes the new version string.
    sed -i.bak "s/\"release_version\": \"v[^\"]*\"/\"release_version\": \"v$new\"/" docs/docs.json && rm docs/docs.json.bak
    grep -q "\"release_version\": \"v$new\"" docs/docs.json || { echo "docs release_version bump failed" >&2; exit 1; }
  fi

  git-cliff --tag "v$new" -o CHANGELOG.md

  # The changelog is for graph's users. This repo's own dogfooding — the
  # review plans, the drift gate, the release plans — reaches no user, so it
  # belongs in `ci:` commits that git-cliff skips (see RELEASING.md). A leak
  # here means a commit was mistyped, and it is worth stopping the release
  # for: v0.12.0 shipped with five internal scout commits as its headline
  # "Added" entries. Retype the offending commit (or, if it is already
  # pushed, add it to the historical skip list in cliff.toml) and re-run.
  if leaked=$(grep -nE 'graph_review_(9000|core|thread_audit)|docs_drift|changelog_entry|compose_changelog|\bscouts?\b' CHANGELOG.md); then
    echo "CHANGELOG.md names graph's own dogfooding — those commits should be ci:" >&2
    echo "$leaked" >&2
    exit 1
  fi

  # The docs changelog is generated by graph's own plans: changelog_entry
  # infers this release's summary (and migration prompt, when consumers
  # must act) once into docs/snippets/changelog/<version>/ — the files the
  # review below is for; they are curated by hand from then on — and
  # compose_changelog rebuilds docs/changelog.mdx, which IMPORTS the
  # snippets rather than embedding them, so each piece of prose exists in
  # exactly one file. `publish` composes again, so snippet edits made
  # during the review need no extra step.
  #
  # Both plans read the tags through git-cliff, never this CHANGELOG.md.
  GRAPH_STORAGE=memory graph plan run changelog_entry --input version="v$new" --input formats="$format_delta"
  GRAPH_STORAGE=memory graph plan run compose_changelog --input tag="v$new"

  cat <<EOF

v$new is prepared and NOT committed. Review before publishing:

  docs/snippets/changelog/v$new/   the inferred summary (and migration prompt, if any) — edit freely
  CHANGELOG.md                     the commit rendering — fix a wrong entry by retyping its commit, not here

  git diff --stat

Then:   mise run release:publish     commit, tag v$new, push
Or:     mise run release:abort       drop everything above
EOF
}

# The tree must hold a prepared release and nothing else: every change must
# fall inside release_files, and Cargo.toml must name a version with no tag.
require_prepared() {
  require_main
  local stray
  stray=$(git status --porcelain --untracked-files=all | awk '{print $2}' | grep -vE '^(Cargo\.toml|Cargo\.lock|CHANGELOG\.md|docs/docs\.json|docs/changelog\.mdx|docs/snippets/changelog/)' || true)
  [ -z "$stray" ] || { echo "working tree has changes outside the prepared release:" >&2; echo "$stray" >&2; exit 1; }
  [ -n "$(git status --porcelain)" ] || { echo "nothing is prepared — run scripts/release.sh <patch|minor|major> first" >&2; exit 1; }
  new=$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -1)
  if git rev-parse "v$new" >/dev/null 2>&1; then
    echo "tag v$new already exists — Cargo.toml was not bumped by prepare" >&2; exit 1
  fi
  [ -d "docs/snippets/changelog/v$new" ] || { echo "docs/snippets/changelog/v$new/ is missing — prepare did not finish" >&2; exit 1; }
}

publish() {
  require_prepared
  require_graph
  resolve_release "$new"

  # The review may have edited the snippets; the page imports them, so the
  # recomposition is what carries a changed snippet set (a migration prompt
  # added or removed) into the page. Content edits need nothing.
  GRAPH_STORAGE=memory graph plan run compose_changelog --input tag="v$new"

  git add "${release_files[@]}"
  git commit -q -m "chore(release): v$new"
  git tag -a "v$new" -m "$tag_message"
  git push -q origin main "v$new"

  echo "v$new pushed — binaries build at: https://github.com/tylerdavis/graph/actions"
}

abort() {
  require_prepared
  git checkout -q -- Cargo.toml Cargo.lock CHANGELOG.md docs/docs.json docs/changelog.mdx docs/snippets/changelog
  git clean -qfd docs/snippets/changelog
  echo "dropped the prepared v$new"
}

case "$command" in
  patch|minor|major|current) prepare "$command" ;;
  publish) publish ;;
  abort) abort ;;
  *) echo "unknown command: $command (patch|minor|major|current|publish|abort)" >&2; exit 1 ;;
esac
