#!/usr/bin/env bash
# Cut a release: bump the workspace version, regenerate CHANGELOG.md,
# commit, tag v<version>, and push. The pushed tag triggers the
# .github/workflows/release.yaml binary build.
#
# Usage: scripts/release.sh <patch|minor|major|current>
#   current — tag the existing version without bumping (first release).
set -euo pipefail

level="${1:?usage: release.sh <patch|minor|major|current>}"

# Preconditions: on main, clean tree, up to date with origin — and a
# working graph, because the changelog is generated by graph's own plans
# (changelog_entry, compose_changelog). Validating here fails fast on a
# missing or too-old binary before anything is mutated.
branch=$(git rev-parse --abbrev-ref HEAD)
[ "$branch" = "main" ] || { echo "must release from main (on $branch)" >&2; exit 1; }
[ -z "$(git status --porcelain)" ] || { echo "working tree not clean" >&2; exit 1; }
git fetch -q origin main
[ "$(git rev-parse HEAD)" = "$(git rev-parse origin/main)" ] || { echo "main is not in sync with origin" >&2; exit 1; }
command -v graph >/dev/null || { echo "graph not found on PATH — the changelog plans need it (mise run install)" >&2; exit 1; }
GRAPH_STORAGE=memory graph plan validate compose_changelog >/dev/null \
  || { echo "compose_changelog does not validate — graph on PATH too old? (needs >= v0.10.0 for filter steps)" >&2; exit 1; }

current=$(sed -n 's/^version = "\(.*\)"$/\1/p' Cargo.toml | head -1)
IFS=. read -r major minor patch <<<"$current"
case "$level" in
  major)   new="$((major + 1)).0.0" ;;
  minor)   new="$major.$((minor + 1)).0" ;;
  patch)   new="$major.$minor.$((patch + 1))" ;;
  current) new="$current" ;;
  *) echo "unknown level: $level" >&2; exit 1 ;;
esac

if git rev-parse "v$new" >/dev/null 2>&1; then
  echo "tag v$new already exists" >&2; exit 1
fi

# The file-version constants (docs/reference/file-versions.mdx) at a ref, one
# "<name> <version>" per line. A ref that predates a file reads as format 1,
# which is what an unversioned file means.
format_table() {
  local ref=$1
  for spec in \
    "config crates/graph-config/src/format.rs CONFIG_FORMAT" \
    "plan crates/graph-core/src/format.rs PLAN_FORMAT" \
    "tool crates/graph-core/src/format.rs TOOL_FORMAT" \
    "store crates/graph-store/src/file.rs STORE_FORMAT"; do
    set -- $spec
    source=$(git show "$ref:$2" 2>/dev/null || true)
    version=$(printf '%s\n' "$source" | sed -n "s/^pub const $3: u32 = \([0-9]*\);.*/\1/p" | head -1)
    echo "$1 ${version:-1}"
  done
}

# A file-version bump or a breaking commit is a release-level decision, not a
# patch: pre-1.0 it needs at least a minor, from 1.0 on it needs a major.
# Checked before anything is mutated, alongside the tag check above.
last_tag=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null || true)
format_delta=""
if [ -n "$last_tag" ]; then
  format_delta=$(paste -d' ' <(format_table "$last_tag") <(format_table HEAD) \
    | awk '$2 != $4 { printf "%s %s→%s\n", $1, $2, $4 }' | paste -sd',' - | sed 's/,/, /g')
fi
breaking=$(git-cliff --tag "v$new" --unreleased --context 2>/dev/null \
  | jq '[.[] | .commits[]? | select(.breaking == true)] | length')
if [ -n "$format_delta" ] || [ "${breaking:-0}" -gt 0 ]; then
  echo "release carries breaking changes: ${breaking:-0} breaking commit(s)${format_delta:+, file-version bump(s): $format_delta}"
  needed=$([ "$major" -ge 1 ] && echo major || echo minor)
  case "$level:$needed" in
    major:*|minor:minor|current:*) ;;
    *) echo "a breaking release needs at least a $needed bump (got $level)" >&2; exit 1 ;;
  esac
fi

# A release needs at least one changelog-worthy commit. git-cliff emits no
# section at all for a tag whose commits are every one ci:/chore:/test:, and
# the release would then strand halfway — version bumped, CHANGELOG.md
# rewritten, then changelog_entry failing with no release to describe and a
# dirty tree to clean up by hand. Checked here, before anything is mutated.
worthy=$(git-cliff --tag "v$new" --unreleased --context 2>/dev/null \
  | jq '[.[] | .commits[]? | select(.group != null)] | length')
[ "$worthy" -gt 0 ] || {
  echo "nothing to release: no changelog-worthy commits since the last tag" >&2
  echo "(everything since is ci:/chore:/test:, which the changelog skips)" >&2
  exit 1
}

echo "releasing v$new (was $current)"

if [ "$level" != "current" ]; then
  # Bump the single workspace version (crates inherit it). The full-line
  # anchor matches only the workspace field, so plain s/// is safe — and
  # portable: GNU-only "0,/re/" addressing silently no-ops on BSD sed.
  sed -i.bak "s/^version = \"$current\"\$/version = \"$new\"/" Cargo.toml && rm Cargo.toml.bak
  grep -q "^version = \"$new\"\$" Cargo.toml || { echo "version bump failed" >&2; exit 1; }
  # Refresh Cargo.lock's version entries.
  cargo update -q --workspace
  # Keep the docs in step: {{release_version}} feeds the installation
  # page, download cards, and cookbook image pins. Key-anchored so a
  # drifted value fails the grep below instead of shipping stale docs —
  # and since the release commit now touches docs/, it also triggers the
  # Mintlify rebuild that publishes the new version string.
  sed -i.bak "s/\"release_version\": \"v[^\"]*\"/\"release_version\": \"v$new\"/" docs/docs.json && rm docs/docs.json.bak
  grep -q "\"release_version\": \"v$new\"" docs/docs.json || { echo "docs release_version bump failed" >&2; exit 1; }
fi

git-cliff --tag "v$new" -o CHANGELOG.md

# The changelog is for graph's users. This repo's own dogfooding — the review
# plans, the drift gate, the release plans — reaches no user, so it belongs in
# `ci:` commits that git-cliff skips (see RELEASING.md). A leak here means a
# commit was mistyped, and it is worth stopping the release for: v0.12.0 shipped
# with five internal scout commits as its headline "Added" entries. Retype the
# offending commit (or, if it is already pushed, add it to the historical skip
# list in cliff.toml) and re-run.
if leaked=$(grep -nE 'graph_review_(9000|core|thread_audit)|docs_drift|changelog_entry|compose_changelog|\bscouts?\b' CHANGELOG.md); then
  echo "CHANGELOG.md names graph's own dogfooding — those commits should be ci:" >&2
  echo "$leaked" >&2
  exit 1
fi

# The docs changelog is generated by graph's own plans: changelog_entry
# infers this release's summary (and migration prompt, when consumers
# must act) once into docs/snippets/changelog/<version>/ — review those
# files before pushing; they are curated by hand from then on — and
# compose_changelog rebuilds docs/changelog.mdx, which IMPORTS the
# snippets rather than embedding them, so each piece of prose exists in
# exactly one file.
#
# Both plans read the tags through git-cliff, never this CHANGELOG.md.
# The regeneration above and the docs build below are two renderings of
# one set of facts, not a pipeline — so the order here is convenience,
# not a dependency.
GRAPH_STORAGE=memory graph plan run changelog_entry --input version="v$new" --input formats="$format_delta"
GRAPH_STORAGE=memory graph plan run compose_changelog --input tag="v$new"

git add Cargo.toml Cargo.lock CHANGELOG.md docs/docs.json docs/changelog.mdx docs/snippets/changelog
git commit -q -m "chore(release): v$new"
git tag -a "v$new" -m "graph v$new"
git push -q origin main "v$new"

echo "v$new pushed — binaries build at: https://github.com/tylerdavis/graph/actions"
